Pipeline con Integracion Continua2

diff --git a/.github/workflows/decsecops.yml b/.github/workflows/decsecops.yml
--- a/.github/workflows/decsecops.yml
+++ b/.github/workflows/decsecops.yml
@@ -1,4 +1,4 @@
-name: Pipeline DevSecOps
+name: DevSecOps Pipeline
 
 on:
   push:
@@ -9,134 +9,135 @@ on:
 jobs:
   security-pipeline:
     runs-on: ubuntu-latest
-
+    
     steps:
-      # 1. Clonar repositorio
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+    # 1. Clonacion del repositorio
+    - name: Checkout code
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
 
-      # 2. Configurar Node.js
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '18'
-          cache: 'npm'
+    # 2. Configurar Node.js
+    - name: Configurar Node.js
+      uses: actions/setup-node@v4
+      with:
+        node-version: '18'
+        cache: 'npm'
 
-      # Instalar dependencies
-      - name: Instalar dependencias
-        run: npm install
+    # 3. Instalar dependencies
+    - name: Instalar dependencias
+      run: npm install
 
-      # 3. SAST SonarCloud Escaner
-      - name: Escaner SonarCloud
-        uses: SonarSource/sonarcloud-github-action@master
-        env:
-            GITHUB_TOKEN: ${{ secrets.KEY_GIT_TOKEN }}
-            SONAR_TOKEN: ${{ secrets.Token-Sonar-TalleFinal }}
-            with:
-            args: |
-                -Dsonar.projectKey=curso-devsecops2025_Taller-Final
-                -Dsonar.organization="curso-devsecops2025"
-                -Dsonar.sources=.
-                -Dsonar.exclusions="node_modules/**,coverage/**,**/*.test.js"
-                -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
+    # 4. SAST SonarCloud Escaner
+    - name: SonarCloud Escaner
+      uses: SonarSource/sonarcloud-github-action@master
+      env:
+        GITHUB_TOKEN: ${{ secrets.KEY_GIT_TOKEN }}
+        SONAR_TOKEN: ${{ secrets.TOKEN_SONAR_TALLERFINAL }}
+      with:
+        args: >
+          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
+          -Dsonar.organization=tu-organizacion
+          -Dsonar.sources=.
+          -Dsonar.exclusions=node_modules/**,coverage/**,**/*.test.js
+          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
 
-      # 4. Check SonarCloud Quality Gate
-      - name: Check SonarCloud Quality Gate
-        run: |
-          echo "Checking SonarCloud Quality Gate..."
-          # This step will fail if quality gate fails (Critical, High, Medium vulnerabilities)
-          curl -u ${{ secrets.TOKEN_SONAR_TALLERFINAL }}: \
-              "https://sonarcloud.io/api/qualitygates/project_status?projectKey=movies-app-devsecops" \
-            | jq -e '.projectStatus.status == "OK"' 
+    # 5. Chequear SonarCloud Quality Gate
+    - name: Chequear SonarCloud Quality Gate
+      run: |
+        echo "Chequear SonarCloud Quality Gate..."
+        # This step will fail if quality gate fails (Critical, High, Medium vulnerabilities)
+        curl -u ${{ secrets.TOKEN_SONAR_TALLERFINAL }}: \
+          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=movies-app-devsecops" \
+          | jq -e '.projectStatus.status == "OK"'
 
-      # 5. SCA - Chequear Dependencia
-      - name: Chequear OWASP Dependency Check
-        uses: dependency-check/Dependency-Check_Action@main
-        with:
-            project: 'movies-app'
-            path: '.'
-            format: 'JSON'
-            args: >
-                    --enableRetired
-                    --enableExperimental
-                    --failOnCVSS 4
-                    --out reports
+    # 6. SCA - Dependency Check
+    - name: Corre OWASP Dependency Check
+      uses: dependency-check/Dependency-Check_Action@main
+      with:
+        project: 'movies-app'
+        path: '.'
+        format: 'JSON'
+        args: >
+          --enableRetired
+          --enableExperimental
+          --failOnCVSS 4
+          --out reports
 
-      # 6. Chequear Vulnerabilidad Dependencia
-      - name: Chequea Vulnerabilidades de Dependencia
-        run: |
-            if [ -f "reports/dependency-check-report.json" ]; then
-            # Chequeo de Criticidad de vulnerabilidades
-            CRITICA=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity == "CRITICA")] | length' reports/dependency-check-report.json)
-            ALTA=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity == "ALTA")] | length' reports/dependency-check-report.json)
-            MEDIA=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity == "MEDIA")] | length' reports/dependency-check-report.json)
-                        
-            echo "Vulnerabilidad Critica: $CRITICA"
-            echo "Vulnerabilidad: $ALTA"
-            echo "Vulnerabilidad Media: $MEDIA"
-                                
-                if [ "$CRITICA" -gt 0 ] || [ "$ALTA" -gt 0 ] || [ "$MEDIA" -gt 0 ]; then
-                    echo "Pipeline fallido: Vulnerabilidad Critica, Alta, o Media"
-                    exit 1
-                fi
-            fi
+    # 7. Chequear Vulnerabilidad Dependencia
+    - name: Chequea Vulnerabilidades de Dependencia
+      run: |
+        if [ -f "reports/dependency-check-report.json" ]; then
+          # Chequear Vulnerabilidades Critica, Alta, o Media
+          CRITICA=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity == "CRITICA")] | length' reports/dependency-check-report.json)
+          ALTA=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity == "ALTA")] | length' reports/dependency-check-report.json)
+          MEDIA=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity == "MEDIA")] | length' reports/dependency-check-report.json)
+          
+          echo "Vulnerabilidad Critica: $CRITICA"
+          echo "Vulnerabilidad Alta: $ALTA"
+          echo "Vulnerabilidad Media: $MEDIA"
+          
+          if [ "$CRITICA" -gt 0 ] || [ "$ALTA" -gt 0 ] || [ "$MEDIA" -gt 0 ]; then
+            echo " Pipeline fallido: Vulnerabilidad Critica, Alta, o Media "
+            exit 1
+          fi
+        fi
 
-      # 7. Construcción de Imagen Docker
-      - name: Construir Imagen Docker 
-        run: |
-            docker build -t movies-app:${{ github.sha }} .
-            docker tag movies-app:${{ github.sha }} movies-app:latest
+    # 8. Construccion de Imagen Docker
+    - name: Construir Imagen Docker
+      run: |
+        docker build -t movies-app:${{ github.sha }} .
+        docker tag movies-app:${{ github.sha }} movies-app:latest
 
-      # 8. Imagen Seguridad - Scan Trivy
-      - name: Correr Scanner Trivy
-        uses: aquasecurity/trivy-action@master
-        with:
+    # 9. Imagen Seguridad - Scan Trivy
+    - name: Run Trivy vulnerability scanner
+      uses: aquasecurity/trivy-action@master
+      with:
         image-ref: 'movies-app:latest'
         format: 'json'
         output: 'trivy-results.json'
         exit-code: '0'
 
-	  # 9. Chequear Imagen Vulnerabilidad
-      - name: Chequea Imagen Securidad
-        run: |
-            if [ -f "trivy-results.json" ]; then
-            CRITICA=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "CRITICA")] | length' trivy-results.json)
-            ALTA=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "ALTA")] | length' trivy-results.json)
-            MEDIA=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "MEDIA")] | length' trivy-results.json)
-                    
-            echo "Vulnerabilidad Critica: $CRITICA"
-            echo "Vulnerabilidad Alta: $ALTA"
-            echo "vulnerabilidad Media: $MEDIA"
-                    
-                if [ "$CRITICA" -gt 0 ] || [ "$ALTA" -gt 0 ] || [ "$MEDIA" -gt 0 ]; then
-                echo "Pipeline faillido: Errores Criticos, Altos, o Medios en la imagen de Docker"
-                exit 1
-                fi
-            fi
-      # 10. Despliegue de la aplicación (Docker local)
-      - name: Deployar aplicacion
-    run: |
-        echo "Deployando aplicacion..."
-        docker run -d -p 3000:3000 --name movies-app movies-app:latest
-            sleep 10
-            # Verificar que la aplicación esté corriendo
-            curl -f http://localhost:3000 || exit 1
+    # 10. Chequear Imagen Vulnerabilidad
+    - name: Chequear Imagen Seguridad
+      run: |
+        if [ -f "trivy-results.json" ]; then
+          CRITICA=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "CRITICA")] | length' trivy-results.json)
+          ALTA=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "ALTA")] | length' trivy-results.json)
+          MEDIA=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "MEDIA")] | length' trivy-results.json)
+          
+          echo "Vulnerabilidad Critica: $CRITICA"
+          echo "Vulnerabilidad Alta: $ALTA"
+          echo "Vulnerabilidad Media: $MEDIA"
+          
+          if [ "$CRITICA" -gt 0 ] || [ "$ALTA" -gt 0 ] || [ "$MEDIA" -gt 0 ]; then
+            echo " Pipeline fallido: Errores Criticos, Altos, o Medios en la imagen de Docker"
+            exit 1
+          fi
+        fi
 
-      # 11. DAST - OWASP ZAP Analisis
-      - name: OWASP ZAP Analisis
-    uses: zaproxy/action-baseline@v0.10.0
-        with:
+    # 11. Despliegue de la aplicación (Docker local)
+    - name: Deployar Aplicacion
+      run: |
+        echo "Deploying application..."
+        docker run -d -p 3000:3000 --name movies-app movies-app:latest
+        sleep 10
+        # Verificar que la aplicación esté corriendo
+        curl -f http://localhost:3000 || exit 1
+
+    # 12. DAST - OWASP ZAP Analisis
+    - name: Zap Owasp Analisis
+      uses: zaproxy/action-baseline@v0.10.0
+      with:
         target: 'http://localhost:3000'
         rules_file_name: '.zap/rules.tsv'
         cmd_options: '-a'
 
-      # 12. Upload reports as artifacts
-      - name: Upload Security Reports
-    uses: actions/upload-artifact@v4
-       if: always()
-       with:
+    # 13. Carga reporte como artifacto
+    - name: Carga Reporte Securidad
+      uses: actions/upload-artifact@v4
+      if: always()
+      with:
         name: security-reports
         path: |
           reports/
@@ -144,7 +145,7 @@ jobs:
           report_html.html
           report_json.json
 
-    # Cleanup
+    # 14.Cleanup
     - name: Cleanup
       if: always()
       run: |
